Projects/urls.py
from django.contrib import admin
from django.urls import path , include
from django.shortcuts import render

from Urlshortner import views as urlviews
from Todo import views as todoviews
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

#Home page for Django Portfolio
def index(request):
    return render(request , 'index.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , index , name='index'),

    # Url Shortner
    path('Urlshortner/' , include('Urlshortner.urls')),
    path('go/<str:sht>' , urlviews.go , name="go"),

    #Todo
    path('Todo/' , include('Todo.urls')),

    #Resources Projects
    path('SonicRes/' , include('SonicRes.urls')),

    #media files


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

SonicRes/urls.py
from django.urls import path
from SonicRes import views

app_name= 'SonicRes'

urlpatterns = [
    path('index' , views.index , name='index'),
    path('upload' , views.upload , name='upload'),
    path('dashboard' , views.dashboard , name='dashboard'),
]

Todo/urls.py
from django.urls import path

from Todo import views

app_name = 'Todo'
urlpatterns = [
    path('index', views.index , name='index'),
    path('create' , views.create , name='create'),
    path('complete/<str:id>' , views.complete , name='complete'),
    path('delete/<str:id>' , views.delete , name='delete'),
]

Urlshortner/urls.py
from django.urls import path
from . import views

app_name = 'Urlshortner'


urlpatterns = [
    path('index' , views.index , name='index' ),
    path('create' , views.create , name='create'),
]

SonicRes/models.py
from django.db import models

# Create your models here.

class testupload(models.Model):

    title = models.CharField(max_length=1000)
    shortUrl = models.URLField(max_length = 200)
    filex = models.FileField(upload_to ='test')

    def __str__(self):
        return str(self.filex)

Todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=1000)
    date = models.CharField(max_length=50)
    status = models.BooleanField()

    def __str__(self):
        return self.task

Urlshortner/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
    link = models.CharField(max_length=10000)
    uid = models.CharField(max_length=10)

    def __str__(self):
        return self.uid

SonicRes/forms.py
from django import forms
# from .models import testupload
#
# class testform(forms.ModelForm):
#     class Meta():
#         model = testupload
#         fields = ('filex')

SonicRes/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import testupload

# library for post request
import requests




# Create your views here.
def index(request):
    return render(request , 'SonicRes/SonicIndex.html')


def upload(request):
    if request.method == "POST":
        test = testupload(filex = request.FILES['myFile'] ,title = str(request.FILES['myFile']) , shortUrl = '')
        test.save()
        print(test.filex)
        redirectLink = 'https://parasdjango.pythonanywhere.com/media/'+str(test.filex)
        # redirectLink = 'http://127.0.0.1:8000/media/'+str(test.filex)

        test.shortUrl =  'https://parasdjango.pythonanywhere.com/go/'+shortner(redirectLink)
        # test.shortUrl =  'http://127.0.0.1:8000/go/'+shortner(redirectLink)
        test.save()
        print("Uploaded the file" , request.FILES['myFile'])
        # return HttpResponse(str(test.shortUrl))
        return redirect('/SonicRes/dashboard')


#only used to shortn the file url
def shortner(redirectLink):
    Redirectdata = {'link': redirectLink}
    shortUrl = requests.post(url = 'https://parasdjango.pythonanywhere.com/Urlshortner/create', data = Redirectdata)
    # shortUrl = requests.post(url = 'http://127.0.0.1:8000/Urlshortner/create', data = Redirectdata)
    shortUrl = shortUrl.text
    return shortUrl

def dashboard(request):
    userData = testupload.objects.order_by('title')
    print(userData)
    context = {'records': userData}
    return render(request , "SonicRes/dashboard.html" , context=context)

Todo/views.py
from django.shortcuts import render
from .models import Task
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse

# Create your views here.



def index(request):
    task_list = Task.objects.order_by('date')
    row_colors = ["primary" , "secondary" , "success" ,"danger" ,"warning", "info" ,"light" , "dark"]
    return render(request , 'Todo/Todoindex.html' , {"task_list" : task_list , "row_colors":row_colors})

def create(request):
    if request.method == "POST":
        print(request.POST)
        task = request.POST['Newtask']
        date = request.POST['TaskTime'].replace("T"," ")
        status = False
        Newtask = Task(task=task , date=date , status=status)
        Newtask.save()
        # return HttpResponse("Hi Added")
        print("Created new Task :" + request.POST['Newtask'] + "time: " + request.POST['TaskTime'].replace("T"," "))
        return HttpResponseRedirect(reverse('Todo:index'))

def complete(request , id):
    comp_task = Task.objects.get(id=id)
    comp_task.status = True
    comp_task.save()
    print("Completed Task id :" + id)
    return HttpResponse("Completed Task id :" + id)

def delete(request , id):
    del_task = Task.objects.get(id=id)
    del_task.delete()
    print("Deleted Task id :" + id)
    return HttpResponse("Deleted Task id :" + id)

Urlshortner/views.py
from django.shortcuts import render , redirect
from Urlshortner.models import Url
from django.http import HttpResponse
import uuid
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def index(request):
    SResult = False
    return render(request , 'Urlshortner/Urlindex.html')

@csrf_exempt
def create(request):
    SResult = True
    if request.method == 'POST':
        # print(request.POST['link'])
        link = request.POST['link']
        uid = str(uuid.uuid4())[:5]
        new_url = Url(link=link , uid=uid)
        new_url.save()
        # print(new_url)
        return HttpResponse(uid)

def go(request , sht):
    big_url = Url.objects.get(uid=sht)
    return redirect(big_url.link)

templates/SonicRes/SonicIndex.html
<!DOCTYPE html>

{% load static  %}


<html lang="en">
  <head>

    <meta charset="UTF-8">
    <title>Soinc Resources - Paras Chhugani</title>

    {% comment %} boostrap css  {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>





<style>

  #parasBranding{
    width: 200px;
  }
  .testDiv{
    border: 1px solid black;
    /* height: 30px; */
  }

  .drop-zone{
    max-width: 250px;
    height: 250px;
    padding: 25px;
    font-size: 20px;
    font-family: "Quicksand", sans-serif;
    font-weight: 500;
    color: #cccccc;
    border: 4px dashed #009578;
    display: flex;
    text-align: center;
    align-items: center;
    justify-content: center;
    cursor: pointer;

  }
  .drop-zone--over{
    border-style: solid;
  }

  .drop-zone__input{
    display: none;
  }
  .drop-zone__thumb{
    width: 100%;
    height: 100%;
    border-radius: 10px;
    overflow: hidden;
    background-color: #cccccc;
    background-size: cover;
    position: relative;
  }
  .drop-zone__thumb::after{
    content: attr(data-label);
    width: 100%;
    text-align: center;
    position: absolute;
    bottom: 0px;
    left: 0px;
    font-size: 14px;
    color: #fff;
    background: rgba(0, 0, 0, 0.75);
    padding: 5px 0;
  }


</style>


  </head>

  <body>

    <nav class="navbar navbar-light sticky-top" style="border-bottom:10px solid #799abc;background-color: #F6F8FF;">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img id="parasBranding" src="{% static 'img/paras_Branding.png' %}" alt="">
      </a>

    </nav>


    <form class="UploadFile_form" action="{% url 'SonicRes:upload' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-div">

        <div class="drop-zone">
          <span class="drop-zone__prompt">Drop file here or click to upload</span>
          <input type="file" name="myFile" class="drop-zone__input">
        </div>

        <div class="">
          {% comment %} <label for="File-Name">File Name :</label>
          <input type="text" name="File-Name" value="" placeholder=""> {% endcomment %}

          <button type="submit" class="btn btn-primary form-submit" >Upload</button>
        </div>

      </div>

    </form>



  </body>

<script type="text/javascript">
document.querySelectorAll(".drop-zone__input").forEach((inputElement) => {
  const dropZoneElement = inputElement.closest(".drop-zone");

  dropZoneElement.addEventListener("click", (e) => {
    inputElement.click();
  });

  inputElement.addEventListener("change", (e) => {
    if (inputElement.files.length) {
      updateThumbnail(dropZoneElement, inputElement.files[0]);
    }
  });

  dropZoneElement.addEventListener("dragover", (e) => {
    e.preventDefault();
    dropZoneElement.classList.add("drop-zone--over");
  });

  ["dragleave", "dragend"].forEach((type) => {
    dropZoneElement.addEventListener(type, (e) => {
      dropZoneElement.classList.remove("drop-zone--over");
    });
  });

  dropZoneElement.addEventListener("drop", (e) => {
    e.preventDefault();

    if (e.dataTransfer.files.length) {
      inputElement.files = e.dataTransfer.files;
      updateThumbnail(dropZoneElement, e.dataTransfer.files[0]);
    }

    dropZoneElement.classList.remove("drop-zone--over");
  });
});

/**
 * Updates the thumbnail on a drop zone element.
 *
 * @param {HTMLElement} dropZoneElement
 * @param {File} file
 */
function updateThumbnail(dropZoneElement, file) {
  let thumbnailElement = dropZoneElement.querySelector(".drop-zone__thumb");

  // First time - remove the prompt
  if (dropZoneElement.querySelector(".drop-zone__prompt")) {
    dropZoneElement.querySelector(".drop-zone__prompt").remove();
  }

  // First time - there is no thumbnail element, so lets create it
  if (!thumbnailElement) {
    thumbnailElement = document.createElement("div");
    thumbnailElement.classList.add("drop-zone__thumb");
    dropZoneElement.appendChild(thumbnailElement);
  }

  thumbnailElement.dataset.label = file.name;

  // Show thumbnail for image files
  if (file.type.startsWith("image/")) {
    const reader = new FileReader();

    reader.readAsDataURL(file);
    reader.onload = () => {
      thumbnailElement.style.backgroundImage = `url('${reader.result}')`;
    };
  } else {
    thumbnailElement.style.backgroundImage = null;
  }
}


</script>

</html>

templates/SonicRes/dashboard.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for rec in records %}
      <div class="">
        <p>{{ rec.title }}</p>
        <img src= "https://parasdjango.pythonanywhere.com/media/{{ rec.filex }}" width="250px" height="150px"/>
        <!-- <img src= "http://127.0.0.1:8000/media/{{ rec.filex }}" width="250px" height="150px"/> -->
        <p>ShortUrl = {{ rec.shortUrl }}</p>
      </div>

    {% endfor %}
  </body>
</html>

templates/SonicRes/howtouse.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How to Use?</title>
    <link href='https://fonts.googleapis.com/css?family=Jost' rel='stylesheet'>
    <link rel="stylesheet" href="assets/howtouse.css">
</head>

<body>
    <div class="navigationBar">
        <img src="assets/img/free Delvery (1) 1.png" class="logoimg">
        <button type="button" class="howto">How to use?</button>
    </div>
    <div class="leftside">
        <p class="content">Dashboard</p>
        <div class="flashcards">
            <img src="assets/img/dogimage.png" class="imga">
            <p class="insidepng">url.xy/fgrio.png</p>
            <div class="downurl">
                <p class="url" id="url">rl.ly/sfbrei</p>
                <img class="copy" src="assets/img/copy1.png">
                <button class="cp" type="button"></button>
            </div>
        </div>
        <button type="button" class="deletebutton">Delete</button>
    </div>
    <div class="rightside">
        <div class="maindiv">
            <p class="textinside">Upload your files</p>

            <img class="containsimg" src="assets/img/draganddrop.png">

        </div>
    </div>
    <div class="userprofile">
        <img src="assets/img/photo.png" class="photo">
        <!-- <span><button type="button" class="dropdown">\/</button></span> -->
        <div class="dropdown">
            <button class="dropbtn">▼</button>
            <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href="#">Link 2</a>
                <a href="#">Link 3</a>
            </div>
        </div>

    </div>

</body>

</html>

templates/SonicRes/sonicHome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link href='https://fonts.googleapis.com/css?family=Jost' rel='stylesheet'>
    <link rel="stylesheet" href="assets/sonichomestyle.css">

</head>

<body>
    <div class="navigationBar">
        <img src="assets/img/free Delvery (1) 1.png" class="logoimg">
        <button type="button" class="howto">How to Use?</button>
        <button type="button" class="signin">Sign Up/Log in</button>
    </div>
    <div class="leftside">
        <div class="content">
            Save Image/Code on cloud and load them with link
        </div>
        <div class="content1">
            100% Automatically and Free
        </div>
        <img src="assets/img/gian-cescon-00ByEXKcSkA-unsplash 1.png" class="demoimg">
        <div class="downurl">
            <p class="url" id="url">rl.ly/sfbrei</p>
            <img class="copy" src="assets/img/copy1.png">
            <button class="cp" type="button"></button>
        </div>
    </div>
    <div class="shareimg"><img src="assets/img/share1.png"></div>

    <div class="rightside">
        <div class="maindiv">
            <p class="textinside">Upload your files</p>

            <img class="containsimg" src="assets/img/draganddrop.png">

        </div>
    </div>
    </div>
</body>

</html>

templates/SonicRes/upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Page</title>
    <link href='https://fonts.googleapis.com/css?family=Jost' rel='stylesheet'>
    <link rel="stylesheet" href="assets/upload.css" </head>

    <body>
        <div class="navigationBar">
            <img src="assets/img/free Delvery (1) 1.png" class="logoimg">
            <button type="button" class="howto">How to Use?</button>
            <button type="button" class="signin">Sign Up/Log in</button>
        </div>
        <div class="rightside">
            <div class="maindiv">
                <p class="textinside">Upload your files</p>

                <img class="containsimg" src="assets/img/draganddrop.png">

            </div>

        </div>
        <div class="text1">Link to your Resource files stays active for 30 days !
        </div>
        <div class="text2">SignIn / LogIn to extend it to life time ...
        </div>

    </body>

</html>

templates/Todo/Todoindex.html
<!DOCTYPE html>

{% load static %}
{% load define_action %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Todo - Paras Chhugani</title>

    {% comment %} boostrap css  {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="{% static 'img/Todo_favicon.png' %}" type="image/gif" sizes="26x26">

    <style media="screen">
    input{
      border-radius: 15px;
      height: 40px;
    }
    body{
      background-color: #F6F8FF;
    }
      #parasBranding{
        width: 200px;
      }
      .testDiv{
        border: 1px solid black;
        /* height: 30px; */
      }
      #PJ_logo{
        width: 300px;
      }
      .Newtask_Div{
        /* display: flex; */

      }
      .jumbotron{
        padding: 2rem 2rem;
        border-bottom-left-radius:50px;
        border-bottom-right-radius:50px;
      }
      .Add_task_btn{
        padding: 5px 10px;
        border-radius: 15px;
        margin-bottom: 5px;
        margin-left: 20px;
        background-color:#3264E5;
        font-size:20px;
      }
      .OldTask{
        height: 250px;
        overflow-y: scroll;
      }
      .CompleteTask{
        margin-top: 50px;
      }
    </style>

  </head>
  <body>
    <nav class="navbar navbar-light sticky-top" style="border-bottom:10px solid #3264E5;background-color: #F6F8FF;">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img id="parasBranding" src="{% static 'img/paras_Branding.png' %}" alt="">
      </a>

      <a href="{% url 'Todo:index' %}">
        <img id="PJ_logo"  src="{% static 'img/TD_logo.png' %}" alt="">
      </a>
    </nav>

    <div class="container" id="main" >

      <div class="Newtask_Div jumbotron">

        <form class="" id="Task-form" action="{% url 'Todo:create' %}" method="post">

          {% csrf_token %}
          <h3>New Task :</h3>

          <div class="" >
            <input type="text" class="" id="Newtask"  name="Newtask" placeholder="Task Name :" required style="width:50%;">

            <label for="TaskTime" style="margin-left:10px;">Due Time :</label>
            <input type="datetime-local" id="TaskTime" name="TaskTime">
            <button type="submit" class="btn btn-primary Add_task_btn" style="">Add task</button>
          </div>

        </form>
      </div>

      <div class="OldTask">

        <h2>Current Tasks</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Task</th>
              <th scope="col">Due Time</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% with i=0 %}
              {% for task in task_list %}
                {% if task.status == False %}
                  {% define i as i %}
                  <tr>
                    <th scope="row" class="table-{{ row_colors|random }}">{{ i }}</th>
                    <th scope="row">{{ task.task }}</th>
                    <th scope="row">{{ task.date }}</th>
                    <th scope="row">
                      <button type="button" class="btn btn-success" onclick="task_complete({{ task.id }})">Complete</button>
                       /
                      <button type="button" class="btn btn-warning" onclick="task_delete({{ task.id }})" >Delete</button></th>
                  </tr>
                {% endif %}
              {% endfor %}
            {% endwith %}
          </tbody>
        </table>
      </div>

      <div class="CompleteTask">
        <h2>Completed Task</h2>

        <table class="table">
          <tbody>
            {% with i=0 %}
              {% for task in task_list %}
                {% if task.status == True %}
                  {% define i as i %}
                  <tr class="table-{{ row_colors|random }}">
                    <th scope="row">{{  i  }}</th>
                    <th scope="row">{{ task.task }}</th>
                    <th scope="row">{{ task.date }}</th>
                {% endif %}
              {% endfor %}
            {% endwith %}
          </tbody>
        </table>
      </div>

    </div>


    <script type="text/javascript" id="Calender_seter">
    var now = new Date();
    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
    document.getElementById('TaskTime').value = now.toISOString().slice(0,16);
     </script>

    <script type="text/javascript" id="cpmplete_delete_tasks">

      function task_complete(id) {
        $.ajax({
          type:'GET',
          url:"complete/"+id,
          success: function(data){
            location.reload();
          }
        });
      }

      function task_delete(id) {
        $.ajax({
          type:'GET',
          url:"delete/"+id,
          success: function(data){
            location.reload();
          }
        });
      }

    </script>
  </body>
</html>

templates/Urlshortner/Urlindex.html
<!DOCTYPE html>

{% load static %}


<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Url Shortner - Paras Chhugani</title>

    {% comment %} boostrap css  {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

    <style media="screen">
    body{
      background-color: #FBFBFB;
    }
      #parasBranding{
        width: 200px;
      }
      .testDiv{
        border: 1px solid black;
        /* height: 30px; */
      }
      #US_logo_div{
        display: flex;
        justify-content: center;
      }
      .short_submit{
        display: flex;
        justify-content: center;
      }

      #Result_url_div{
        display: flex;
        justify-content: center;
        align-items:center;

      }
      #PJ_logo{
        width: 350px;
      }

    </style>

  </head>
  <body>
    <nav class="navbar navbar-light sticky-top" style="border-bottom:10px solid #799abc;background-color: #F6F8FF;">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img id="parasBranding" src="{% static 'img/paras_Branding.png' %}" alt="">
      </a>

      <a href="{% url 'Urlshortner:index' %}">
        <img id="PJ_logo"  src="{% static 'img/URLs_logo.png' %}" alt="">
      </a>

    </nav>

    <div class="container" id="main" >

      <div class="row">

        <div class="col ">
          <img src="{% static 'img/VectorG.jpg' %}" alt="" style="width:100%;margin-top:0px;">
        </div>

        <div class="col " style="width:100%;margin-top:100px;" >


          <form class="" id="post-form" action="{% url 'Urlshortner:create' %}" method="post">

            {% csrf_token %}
            <div class="form-group" >
              <label for="exampleInputEmail1"><h1>Enter URL :</h1></label>
              <input type="url" class="form-control" id="link"  name="link" placeholder="https://......." required>
            </div>

            <div class="form-group short_submit">
              <button type="submit" class="btn btn-primary">Short IT !!</button>
            </div>

          </form>


          <div class="container" id="Result_url_div">

            <h3 id="SResult" ></h3>
            <button type="button" onclick="CopyButton()" id="copyB" name="button" style="padding:10px; border-radius:10px;width:70px;margin-left:30px;display:none;">
              <img src="{% static 'img/copy.png' %}" alt="" style="width:30px;">
              <span>copy</span>
            </button>

          </div>


        </div>

      </div>

    </div>
    <script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:"{% url 'Urlshortner:create' %}",
      data:{
        link:$('#link').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
        $('#SResult').html("https://parasdjango.pythonanywhere.com/go/"+data)
        // $('#SResult').html("http://127.0.0.1:8000/go/"+data)
        document.querySelector("#copyB").style.display = "block";
      }
    });
  });


  function CopyButton(){
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($('#SResult').text()).select();
    document.execCommand("copy");
    $temp.remove();

  }


</script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Projects - Paras Chhugani</title>

    {% comment %} boostrap css  {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" href="{% static 'img/favicon.jpg' %}" type="image/gif" sizes="26x26">

    <style media="screen">
      #parasBranding{
        width: 250px;
      }
      #django_nav_logo{
        width: 250px;
        padding-top: 20px;
      }
      a{
        color: black;
      }
      a:hover{
        text-decoration: none;
        color: inherit;
      }
      .projectlist{
        margin-top: 50px;
      }
      .prolist{
        margin: 20px;
      }

      .prolist:hover{
        background-color: #0390fc;
        color: white;
      }


    </style>

  </head>
  <body>
    <nav class="navbar navbar-light" style="border-bottom:10px solid #799abc;">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img id="parasBranding" src="{% static 'img/paras_Branding.png' %}" alt="">
        <img id="django_nav_logo" src="{% static 'img/logo_nav.png' %}" alt="">
      </a>
    </nav>

    <div class="container projectlist">
      <div class="jumbotron">
        <ul class="list-group">
          <li class="list-group-item prolist" style="border-radius:20px;">
            <a href="{% url 'SonicRes:index' %}" >
              <h2>Rescources</h2>
              <span>Forget your static Files ! We are coming soon to make them obsolete !!</span>
            </a>
          </li>

          <li class="list-group-item prolist" style="border-radius:20px;">
            <a href="{% url 'Urlshortner:index' %}" >
              <h2>Url Shortner</h2>
            </a>
          </li>

          <li class="list-group-item prolist" style="border-radius:20px;">
            <a href="{% url 'Todo:index' %}" >
              <h2>To-Do List</h2>
            </a>
          </li>

        </ul>
      </div>
    </div>

  </body>
</html>